# Generated by Django 3.2.5 on 2021-07-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('c_password', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
            ],
        ),
    ]
