# Generated by Django 3.2.5 on 2021-08-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0005_add_categories_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_user_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('reg_date', models.CharField(max_length=100)),
            ],
        ),
    ]
