# Generated by Django 3.2.5 on 2021-08-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0007_add_equipment_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_equipment_database',
            name='photos',
            field=models.FileField(null=True, upload_to='documents'),
        ),
    ]
