# Generated by Django 3.2.5 on 2021-08-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0010_add_newreservation_database_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_invoiceconfig_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=100)),
                ('issue_date', models.CharField(max_length=100)),
                ('due_date', models.CharField(max_length=100)),
                ('created', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
