# Generated by Django 3.2.5 on 2021-08-06 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0011_add_invoiceconfig_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_categories_database',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
