# Generated by Django 3.2.5 on 2021-08-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0014_user_drill_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='check_user_drill_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('start_dt', models.CharField(max_length=100)),
                ('end_dt', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
            ],
        ),
    ]
